# Generated by Django 5.2.8 on 2025-11-09 14:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SportEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Cím')),
                ('description', models.TextField(verbose_name='Leírás')),
                ('start_date_time', models.DateTimeField(verbose_name='Kezdés időpontja')),
                ('end_date_time', models.DateTimeField(blank=True, null=True, verbose_name='Befejezés időpontja')),
                ('duration_minutes', models.IntegerField(blank=True, help_text='Esemény várható időtartama percben', null=True, validators=[django.core.validators.MinValueValidator(15)], verbose_name='Időtartam (perc)')),
                ('location_name', models.CharField(max_length=200, verbose_name='Helyszín neve')),
                ('location_address', models.CharField(blank=True, max_length=300, null=True, verbose_name='Pontos cím')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Földrajzi szélesség')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Földrajzi hosszúság')),
                ('max_participants', models.IntegerField(validators=[django.core.validators.MinValueValidator(2)], verbose_name='Maximum résztvevők száma')),
                ('min_participants', models.IntegerField(default=2, help_text='Hány fő alatt nem jön létre az esemény', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Minimum résztvevők száma')),
                ('difficulty', models.CharField(choices=[('easy', 'Kezdő'), ('medium', 'Közepes'), ('hard', 'Haladó')], default='medium', max_length=20, verbose_name='Nehézségi szint')),
                ('is_public', models.BooleanField(default=True, help_text='Mindenki láthatja és jelentkezhet', verbose_name='Nyilvános')),
                ('requires_approval', models.BooleanField(default=False, help_text='A szervező jóváhagyása szükséges a jelentkezéshez', verbose_name='Jóváhagyás szükséges')),
                ('is_free', models.BooleanField(default=True, verbose_name='Ingyenes')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Részvételi díj', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ár (Ft)')),
                ('status', models.CharField(choices=[('upcoming', 'Közelgő'), ('ongoing', 'Folyamatban'), ('completed', 'Befejezett'), ('cancelled', 'Törölve')], default='upcoming', max_length=20, verbose_name='Státusz')),
                ('notes', models.TextField(blank=True, help_text='Egyéb fontos információk', null=True, verbose_name='Megjegyzések')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Létrehozva')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Frissítve')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL, verbose_name='Szervező')),
                ('sport_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='accounts.sporttype', verbose_name='Sportág')),
            ],
            options={
                'verbose_name': 'Sportesemény',
                'verbose_name_plural': 'Sportesemények',
                'ordering': ['start_date_time'],
            },
        ),
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Függőben'), ('confirmed', 'Megerősítve'), ('cancelled', 'Lemondva'), ('rejected', 'Elutasítva')], default='pending', max_length=20, verbose_name='Státusz')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Jelentkezés időpontja')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Megerősítés időpontja')),
                ('notes', models.TextField(blank=True, help_text='Üzenet a szervezőnek', null=True, verbose_name='Megjegyzés')),
                ('rating', models.IntegerField(blank=True, help_text='Esemény értékelése 1-5 csillag', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MinValueValidator(5)], verbose_name='Értékelés')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='Visszajelzés')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_participations', to=settings.AUTH_USER_MODEL, verbose_name='Résztvevő')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='events.sportevent', verbose_name='Esemény')),
            ],
            options={
                'verbose_name': 'Résztvevő',
                'verbose_name_plural': 'Résztvevők',
                'ordering': ['joined_at'],
            },
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='event_images/', verbose_name='Kép')),
                ('caption', models.CharField(blank=True, max_length=200, null=True, verbose_name='Képaláírás')),
                ('is_primary', models.BooleanField(default=False, help_text='Ez a kép jelenik meg az esemény előnézetben', verbose_name='Elsődleges kép')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Feltöltve')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='events.sportevent', verbose_name='Esemény')),
            ],
            options={
                'verbose_name': 'Esemény kép',
                'verbose_name_plural': 'Esemény képek',
                'ordering': ['-is_primary', '-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='sportevent',
            index=models.Index(fields=['start_date_time', 'status'], name='events_spor_start_d_428a03_idx'),
        ),
        migrations.AddIndex(
            model_name='sportevent',
            index=models.Index(fields=['latitude', 'longitude'], name='events_spor_latitud_ef1a59_idx'),
        ),
        migrations.AddIndex(
            model_name='sportevent',
            index=models.Index(fields=['sport_type', 'status'], name='events_spor_sport_t_9f4da8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventparticipant',
            unique_together={('event', 'user')},
        ),
    ]
