# Generated by Django 5.0.1 on 2026-03-02 10:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventparticipant',
            name='rating',
            field=models.IntegerField(blank=True, help_text='Esemény értékelése 1-5 csillag', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Értékelés'),
        ),
        migrations.AlterField(
            model_name='sportevent',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Részvételi díj', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ár (Ft)'),
        ),
    ]
