# Generated by Django 5.0.1 on 2026-03-04 08:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_eventparticipant_rating_alter_sportevent_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportevent',
            name='reserved_spots',
            field=models.IntegerField(default=1, help_text='Hány barátoddal szervezed az eseményt?', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Foglalt helyek száma'),
        ),
    ]
