# Generated by Django 5.0.1 on 2026-03-04 08:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_sportevent_reserved_spots'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventparticipant',
            name='extra_guests',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Plusz vendégek száma'),
        ),
        migrations.AlterField(
            model_name='sportevent',
            name='reserved_spots',
            field=models.IntegerField(default=0, help_text='Hány barátoddal szervezed az eseményt?', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Foglalt helyek száma'),
        ),
    ]
