# Generated by Django 5.0.1 on 2026-02-19 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('join_request', 'Új jelentkezés'), ('join_approved', 'Jelentkezés jóváhagyva'), ('join_rejected', 'Jelentkezés elutasítva'), ('join_cancelled', 'Jelentkezés lemondva')], max_length=30, verbose_name='Típus')),
                ('title', models.CharField(max_length=200, verbose_name='Cím')),
                ('message', models.TextField(verbose_name='Üzenet')),
                ('is_read', models.BooleanField(default=False, verbose_name='Olvasott')),
                ('related_event_id', models.IntegerField(blank=True, null=True)),
                ('related_event_title', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Létrehozva')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Címzett')),
            ],
            options={
                'verbose_name': 'Értesítés',
                'verbose_name_plural': 'Értesítések',
                'ordering': ['-created_at'],
            },
        ),
    ]
