# Generated by Django 5.0.1 on 2026-03-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('join_request', 'Új jelentkezés'), ('join_approved', 'Jelentkezés jóváhagyva'), ('join_rejected', 'Jelentkezés elutasítva'), ('join_cancelled', 'Jelentkezés lemondva'), ('event_rated', 'Új értékelés')], max_length=30, verbose_name='Típus'),
        ),
    ]
