# Generated by Django 5.2.8 on 2025-11-09 14:08

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Sportág neve')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Leírás')),
                ('icon', models.CharField(blank=True, help_text="Pl: 'football', 'basketball', 'running'", max_length=50, null=True, verbose_name='Ikon név')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktív')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Létrehozva')),
            ],
            options={
                'verbose_name': 'Sportág',
                'verbose_name_plural': 'Sportágak',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('bio', models.TextField(blank=True, max_length=500, null=True, verbose_name='Bemutatkozás')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='Profilkép')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefonszám')),
                ('default_latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Alapértelmezett földrajzi szélesség', max_digits=9, null=True, verbose_name='Alapértelmezett szélesség')),
                ('default_longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Alapértelmezett földrajzi hosszúság', max_digits=9, null=True, verbose_name='Alapértelmezett hosszúság')),
                ('default_location_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Alapértelmezett helyszín neve')),
                ('default_search_radius', models.IntegerField(default=10, help_text='Hány km-es körzetben keressen eseményeket', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Alapértelmezett keresési sugár (km)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Létrehozva')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Frissítve')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Felhasználó',
                'verbose_name_plural': 'Felhasználók',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserSportPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_level', models.CharField(choices=[('beginner', 'Kezdő'), ('intermediate', 'Haladó'), ('advanced', 'Profi')], default='intermediate', max_length=20, verbose_name='Szint')),
                ('interest_level', models.IntegerField(default=5, help_text='1-10 skálán mennyire érdekli ez a sportág', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Érdeklődési szint')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Létrehozva')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Frissítve')),
                ('sport_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.sporttype', verbose_name='Sportág')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sport_preferences', to=settings.AUTH_USER_MODEL, verbose_name='Felhasználó')),
            ],
            options={
                'verbose_name': 'Sportág preferencia',
                'verbose_name_plural': 'Sportág preferenciák',
                'ordering': ['-interest_level'],
                'unique_together': {('user', 'sport_type')},
            },
        ),
    ]
